### ISSUE TITLE
Custom admin url

### ISSUE THREAD

**Issue by bee-keeper** [nephila/django-ckeditor-filebrowser-filer#17]
Is there a way to pass in the value for base_admin if you use a custom admin url?

Thanks,

**Comment by yakky** [comment]
You mean the urls set in the javascript files?
It's planned, but I'm struggling to find a good / extendable solution for this
Any opinion / advice?

**Comment by bee-keeper** [comment]
Yes. I'm going to have to do this so can PR.

Could simply do as you are now and hit up your reverse url view?

**Comment by yakky** [comment]
It would be great if you could contribute a PR
Sure, let's leverage the existing "reverse url view".
