### ISSUE TITLE
"jQuery" is scoped in Django 1.9 admin and thus unavailable for "jQuery.get()" calls, crashing plugin.

### ISSUE THREAD

**Issue by rafalp** [nephila/django-ckeditor-filebrowser-filer#19]
Culprit appears to be following line:

    jQuery.get('/filebrowser_filer/url_reverse/', { url_name: "admin:filer-directory_listing-last"}, function(data) {

This call fails with `Cannot read property 'get' of undefined`, and rightly so as jquery within Django's admin is namespaced to `django.jQuery`, not to `jquery`.

**Comment by yakky** [comment]
Could you provide the console error?
the ``jQuery`` namespace is local to the function as it's passed to it https://github.com/nephila/django-ckeditor-filebrowser-filer/blob/develop/ckeditor_filebrowser_filer/static/djangocms_text_ckeditor/ckeditor/plugins/filerimage/plugin.js#L1 by picking one of the global namespaces https://github.com/nephila/django-ckeditor-filebrowser-filer/blob/develop/ckeditor_filebrowser_filer/static/djangocms_text_ckeditor/ckeditor/plugins/filerimage/plugin.js#L78

**Comment by rafalp** [comment]
Yes, I have realised that this is de-facto fixed issue, but apparently `pip install` installs `django-ckeditor-filebrowser-filer (0.1.1.post1)` that lacks this implementation:

```
CKEDITOR.plugins.add( 'filerimage', {
    lang: 'en,it',
    icons: 'filerimage',
    init: function( editor ) {
                lang = editor.lang.filerimage,
        editor.addCommand( 'filerImageDialog', new CKEDITOR.dialogCommand( 'filerImageDialog' ) );

        editor.ui.addButton( 'FilerImage', {
                label: lang.name,
                    command: 'filerImageDialog',
                    toolbar: 'insert',
            icon: 'filerimage'
                });

        if ( editor.contextMenu ) {
            editor.addMenuGroup( 'Filer' );
            editor.addMenuItem( 'imageItem', {
                label: lang.edit,
                icon: this.path + 'icons/filerimage.png',
                command: 'filerImageDialog',
                group: 'Filer'
            });

            editor.contextMenu.addListener( function( element ) {
                if ( element.getAscendant( 'img', true ) ) {
                    return { imageItem: CKEDITOR.TRISTATE_OFF };
                }
            });
        }
        CKEDITOR.scriptLoader.load( this.path + '../../../../filer/js/popup_handling.js' );
        CKEDITOR.dialog.add( 'filerImageDialog', this.path + 'dialogs/filerImageDialog.js' );

        var dialog = CKEDITOR.dialog.getCurrent();

        jQuery.get('/filebrowser_filer/url_reverse/', { url_name: "admin:filer-directory_listing-last"}, function(data) {

        });
    }
});
```

Console error points to this file and complains that `Cannot read property 'get' of undefined` on line with `jQuery.get`.

**Comment by yakky** [comment]
@rafalp I'l release 0.2 soon In the meantime to ``pip install django-ckeditor-filebrowser-filer==0.2b12`` which contains the fix

**Comment by yakky** [comment]
@rafalp version 0.2 has been released, thanks for reporting this!
