### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by caliph007** [nephila/django-ckeditor-filebrowser-filer#3]
I am having several issues setting up your module.
Could you go a little bit into more detail how to configure ckeditor?

**Comment by yakky** [comment]
@caliph007 which issues exactly?

**Comment by caliph007** [comment]
I integrate your code:
1) pip install ...
2) add to applications
3) make sure canonical on CKeditor is configured
4) add your url(..)
5) add "filerimage" to plugins in Settings
6) add button to toolbar: "FilerImage" in Settings

Then I have the CKeditor on page, it shows your button, I press it, a pop-up shows and the JS console shows the following error:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

I I click the magnifying glass the url changes to "admin/filer/folder/1/list/". I assume that should not happen. it should open a pop-up where I can browse images and select the desired on.

If you need any more details pls let me know. Any help is appreciated.

**Comment by yakky** [comment]
@caliph007 the issue with the filer path should have been fixed in 2.0b2
In filer 1.1 the path to the javascript has changed: 2.0.b2 should work well with 1.1 now

**Comment by caliph007** [comment]
I see. 
I installed with pip install .. and this still gives me the 0.1.1.post1 version.
Whats the best way to install 2.0b2 ?

**Comment by caliph007** [comment]
I have tested it:
Fresh virtualenv:
django-ckeditor-filebrowser-filer==0.2.0b2
django-ckeditor==5.0.3
django-filer==1.1.1

and still:
Console shows the error:
GET /static/filer/js/popup_handling.js

**Comment by yakky** [comment]
@caliph007 have you installed the views as stated in documentation? support for django-ckeditor has been introduced in 0.2b6. Previous versions were not compatible with django-ckeditor but only with djangocms-text-ckeditor

**Comment by yakky** [comment]
closing this due to lack of feedback. Feel free to reopen / add more feedback if needed
