### ISSUE TITLE
django 2.0 support

### ISSUE THREAD

**Issue by cyberbudy** [nephila/django-ckeditor-filebrowser-filer#30]
File "/lib/python3.6/site-packages/ckeditor_filebrowser_filer/views.py", line 7, in <module>
    from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'

There is an error using django 2.0

**Comment by yakky** [comment]
@cyberbudy we need to wait for divio/django-filer#1030

**Comment by bculpepper** [comment]
Any update on this? I would really love to use this on a Django 2 app.

**Comment by yakky** [comment]
It's fixed in #37  which will be released in 0.3.0 due in the next hours

Thanks a lot for your patience
