### ISSUE TITLE
No select button

### ISSUE THREAD

**Issue by maartinez** [nephila/django-ckeditor-filebrowser-filer#31]
I open popup with ckeditor, there is a button to insert image. Click on that and popup to select image from filer comes in. On that popup it is not possible to select image because there is no select button.

Here is my requirements file, maybe you could reproduce this bug. Thanks.
[req.txt](https://github.com/nephila/django-ckeditor-filebrowser-filer/files/1574901/req.txt)

**Comment by svandeneertwegh** [comment]
I have the same problem too.

**Comment by maartinez** [comment]
I think that I located the line where the bug is. I did some temporary workaround and it works for me. I use djangocms_text_ckeditor so I went to static>djangocms_text_ckeditor>ckeditor>plugins>filerimage>dialogs>filerImageDialog.js

There are these lines:
if (editor.filer_version < 1.2)
var picker = 't=file_ptr';

If you change "t=file_ptr" to "_pick=file" like in the line below, it works with my dependencies.

**Comment by yakky** [comment]
@maartinez which django-filer / djangocms-text-ckeditor version are you on?

**Comment by maartinez** [comment]
@yakky I'm on django-filer==1.3.0 and djangocms-text-ckeditor==3.5.1. There is also my requirements file attached in the first post.

**Comment by yakky** [comment]
@maartinez @svandeneertwegh thanks for reporting this.
Issue should be fixed in linked PR
Would you have the chance to test it?

**Comment by rocchidavide** [comment]
I have the same problem
django-filer==1.3.0
django-ckeditor==5.4.0
django-ckeditor-filebrowser-filer==0.2.3

**Comment by yakky** [comment]
@rocchidavide could you try the linked pr?
```
pip uninstall django-ckeditor-filebrowser-filer && pip install https://github.com/nephila/django-ckeditor-filebrowser-filer/archive/hotfix/filer_1.3.zip
```

**Comment by rocchidavide** [comment]
Ok Yakki, it seems to work

**Comment by yakky** [comment]
@rocchidavide thanks for the confirmation.
A new release is on the way

**Comment by rocchidavide** [comment]
Thanks to you for this extension :)

**Comment by yakky** [comment]
@maartinez @svandeneertwegh @rocchidavide version 0.2.4  released!

**Comment by maartinez** [comment]
@yakky I couldn't respond earlier, sorry. Looks like it's working for me also. Thank you :)

**Comment by svandeneertwegh** [comment]
@yakky Good work!

**Comment by yakky** [comment]
Thanks to all of you for helping with this!
