### ISSUE TITLE
Problem to change (modify src) an existing image

### ISSUE THREAD

**Issue by mateuspadua** [nephila/django-ckeditor-filebrowser-filer#35]
Click in "Edit Image"
![image](https://user-images.githubusercontent.com/515075/37734801-fea272fa-2d2a-11e8-8bca-72d8abecc839.png)

then the image changes normally
![image](https://user-images.githubusercontent.com/515075/37734962-74e780cc-2d2b-11e8-80a6-d274c403b7ca.png)

Save your admin form
![image](https://user-images.githubusercontent.com/515075/37735025-a2f28606-2d2b-11e8-9c54-a1044f64e649.png)

After of page reloaded, see again the ckeditor and realize that the image keep the same:
![image](https://user-images.githubusercontent.com/515075/37735207-1aab79b4-2d2c-11e8-83de-ec0df7022084.png)

I found one solution and soon i am going to do a PR :)

**Comment by yakky** [comment]
@mateuspadua thanks for reporting this and proposing the fix, it's awesome :100:

**Comment by mateuspadua** [comment]
:) 👍
