### ISSUE TITLE
URL pattern incompatible with Django 2.2.25/3.1.14/3.2.10

### ISSUE THREAD

**Issue by dhepper** [nephila/django-ckeditor-filebrowser-filer#41]
[This change](https://github.com/django/django/commit/d4dcd5b9dd9e462fec8220e33e3e6c822b7e88a6) in Django 2.2.25/3.1.14/3.2.10 breaks django-ckeditor-filebrowser-filer, because the path `/filebrowser_filer/filer_version/` no longer matches any URL definitions.

Before this change, [this URL definition](https://github.com/nephila/django-ckeditor-filebrowser-filer/blob/0.3.0/ckeditor_filebrowser_filer/urls.py#L12) would match because it doesn't start with a caret (`^`):

    url(r'version/$', filer_version, name='filer_version'),

I'd open a PR, but I'm not sure if the proper solution would be to fix the URL definition or the JavaScript that requests this URL.

As a quick workaround, I added this URL definition to my project's `urls.py`:

    url(r'^filebrowser_filer/filer_', include('ckeditor_filebrowser_filer.urls')),

**Comment by corentinbettiol** [comment]
Thanks, your workaround helped me made this project work (using the develop branch).
