### ISSUE TITLE
The alignment value translates into the source code and causes not work

### ISSUE THREAD

**Issue by Nekmo** [nephila/django-ckeditor-filebrowser-filer#6]
I put an image aligned to the right but does not work in Spanish. This is because translates the value of "right" to "Derecho".

![right1](https://cloud.githubusercontent.com/assets/740106/14226704/1437707e-f8ea-11e5-84c9-dccdf8414467.png)

![right2](https://cloud.githubusercontent.com/assets/740106/14226705/1cfa7c7e-f8ea-11e5-8318-81a4d311d77f.png)

**Comment by yakky** [comment]
Ouch, this is nasty. Thanks for reporting this

**Comment by yakky** [comment]
@Nekmo Version 0.2b3 should fix it (fix at fd3be2415231d5dbd23dd6c42a16071405f2f0d8)

**Comment by Nekmo** [comment]
Yes, It works perfect :D 

Thanks!
![amazon_xenoblade9](https://cloud.githubusercontent.com/assets/740106/14410211/0ec2d55c-ff2a-11e5-81f3-707afb1bb5c6.png)

**Comment by yakky** [comment]
@Nekmo thanks for reporting and checking
