### ISSUE TITLE
Add FilerImage button

### ISSUE THREAD

**Issue by jtoonyspe** [nephila/django-ckeditor-filebrowser-filer#9]
"Add FilerImage button to you CKEditor configuration."

How do I do this? Every time I try, it breaks ckeditor to where it doesn't load in the cms page.

I've tried adding 'filerimage', to the extraPlugins list, and then adding 'Filer Image' to the toolbar, but that breaks as well. Can't get this working.

**Comment by yakky** [comment]
@jtoonyspe we're going to address this soon

**Comment by yakky** [comment]
@jtoonyspe please check the updated readme, I hope it's clearer now
